defaults: &defaults
  fluent_host:   '192.168.11.242'
  fluent_port:   24224
  tag:           'couponDeliverer.rails.log'
  messages_type: 'string'

development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults